// angular/l-shoppingapp/src/app/components/shoppingform.component.ts
import {Component,OnInit} from '@angular/core';
import {ShoppingItem} from '../models/shoppingitem.model';
import {ShoppingService} from '../services/shoppingservice.service'
import {LoginService} from '../services/loginservice.service';
import {Router} from '@angular/router';

@Component({
	selector:"shoppingform",
	templateUrl:"./shoppingform.component.html",
	styleUrls:["./shoppingform.component.css"]
})
export class ShoppingForm implements OnInit {
	
	item:ShoppingItem = new ShoppingItem("",0,0,0);
	
	constructor(private shopping:ShoppingService,private login:LoginService,private router:Router) {}
	
	ngOnInit() {
		if(!this.login.isUserLogged()) {
			this.router.navigate(["/"]);
		}
	}
	
	addItem() {
		this.shopping.addItem(this.item).subscribe(
			data => console.log(data),
			error => console.log(error),
			() => {
				this.item = new ShoppingItem("",0,0,0)
			}
		)
	}
}
<div class="container">
	<form (ngSubmit)="addItem()" #shoppingForm="ngForm">
		<div class="form-group">
			<label for="type">Type</label>
			<input type="text"
					name="type"
					id="type"
					class="form-control"
					[(ngModel)]="item.type"/>
		</div>
		<div class="form-group">
			<label for="count">Count</label>
			<input type="number"
					name="count"
					id="count"
					class="form-control"
					[(ngModel)]="item.count"/>
		</div>
		<div class="form-group">
			<label for="price">Price</label>
			<input type="number"
					name="price"
					id="price"
					step="0.01"
					class="form-control"
					[(ngModel)]="item.price"/>
		</div>
		<input type="submit" class="btn btn-primary" value="Add item"/>
	</form>
</div>

// react/60_typescript/05_shopping_app/src/components/ShoppingForm.tsx
import React,{useState} from 'react';
import ShoppingItem from '../models/ShoppingItem';

interface Props {
	addItem(item:ShoppingItem):void;
}

interface State {
	type:string;
	count:number;
	price:number;
}

const ShoppingForm:React.FC<Props> = (props:Props) => {
	
	const [state,setState] = useState<State>({
		type:"",
		count:0,
		price:0
	})
	
	const onChange = (event:React.ChangeEvent<HTMLInputElement>) => {
		setState((state) => {
			return {
				...state,
				[event.target.name]:event.target.value
			}
		})
	}
	
	const onSubmit = (event:React.SyntheticEvent) => {
		event.preventDefault();
		let item = new ShoppingItem(state.type,state.count,state.price,0);
		props.addItem(item);
		setState({
			type:"",
			count:0,
			price:0
		})
	}
	
	return(
		<form onSubmit={onSubmit}>
			<label htmlFor="type">Type</label>
			<input type="text"
					name="type"
					id="type"
					onChange={onChange}
					value={state.type}/>
			<br/>
			<label htmlFor="count">Count</label>
			<input type="number"
					name="count"
					id="count"
					onChange={onChange}
					value={state.count}/>
			<br/>
			<label htmlFor="price">Price</label>
			<input type="number"
					name="price"
					id="price"
					onChange={onChange}
					value={state.price}/>
			<br/>
			<input type="submit" value="Add"/>
		</form>
	)
}

export default ShoppingForm;
