// angular/l-shoppingapp/src/app/components/shoppingform.component.ts
import {Component,OnInit} from '@angular/core';
import {ShoppingItem} from '../models/shoppingitem.model';
import {ShoppingService} from '../services/shoppingservice.service'
import {LoginService} from '../services/loginservice.service';
import {Router} from '@angular/router';

@Component({
	selector:"shoppingform",
	templateUrl:"./shoppingform.component.html",
	styleUrls:["./shoppingform.component.css"]
})
export class ShoppingForm implements OnInit {
	
	item:ShoppingItem = new ShoppingItem("",0,0,0);
	
	constructor(private shopping:ShoppingService,private login:LoginService,private router:Router) {}
	
	ngOnInit() {
		if(!this.login.isUserLogged()) {
			this.router.navigate(["/"]);
		}
	}
	
	addItem() {
		this.shopping.addItem(this.item).subscribe(
			data => console.log(data),
			error => console.log(error),
			() => {
				this.item = new ShoppingItem("",0,0,0)
			}
		)
	}
}
<div class="container">
	<form (ngSubmit)="addItem()" #shoppingForm="ngForm">
		<div class="form-group">
			<label for="type">Type</label>
			<input type="text"
					name="type"
					id="type"
					class="form-control"
					[(ngModel)]="item.type"/>
		</div>
		<div class="form-group">
			<label for="count">Count</label>
			<input type="number"
					name="count"
					id="count"
					class="form-control"
					[(ngModel)]="item.count"/>
		</div>
		<div class="form-group">
			<label for="price">Price</label>
			<input type="number"
					name="price"
					id="price"
					step="0.01"
					class="form-control"
					[(ngModel)]="item.price"/>
		</div>
		<input type="submit" class="btn btn-primary" value="Add item"/>
	</form>
</div>

// react/50_shopping_app/04_stage_redux/frontend/src/components/ShoppingForm.js
import {useState} from 'react';
import {useDispatch,useSelector} from 'react-redux';
import {add} from '../actions/shoppingActions';

const ShoppingForm = (props) => {

	const [state,setState] = useState({
		type:"",
		count:0,
		price:0
	})
	
	const appState = useSelector(state => state);
	
	const dispatch = useDispatch();
	
	const onChange = (event) => {
		setState((state) => {
			return {
				...state,
				[event.target.name]:event.target.value
			}
		})
	};
	
	const onSubmit = (event) => {
		event.preventDefault();
		let item = {
			...state
		}
		dispatch(add(appState.login.token,item));
		setState({
			type:"",
			count:0,
			price:0
		})
	}
	return(
		<div style={{
			backgroundColor:"lightgreen",
			width:"40%",
			margin:"auto"
		}}>
			<form onSubmit={onSubmit} className="mb-3">
				<label htmlFor="type" className="form-label">Type:</label>
				<input type="text"
						name="type"
						id="type"
						className="form-control"
						onChange={onChange}
						value={state.type}/>
				<label htmlFor="count" className="form-label">Count:</label>
				<input type="number"
						name="count"
						id="count"
						className="form-control"
						onChange={onChange}
						value={state.count}/>
				<label htmlFor="price" className="form-label">Price:</label>
				<input type="number"
						name="price"
						id="price"
						className="form-control"
						step="0.01"
						onChange={onChange}
						value={state.price}/>
				<input type="submit" className="btn btn-primary" value="Add"/>
			</form>
		</div>
	)
}

export default ShoppingForm;
